apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  storageClassName: admstor
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: admstor
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storagedemo
  labels:
    name: pvcdemo
spec:
  containers:
    - name: democontainer
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pvstor
          mountPath: /usr/share/nginx/html
  volumes:
    - name: pvstor
      persistentVolumeClaim:
        claimName: mypvc



        #Recap
        # 1 creating a persistent volume, and from it creating a persistent volume claim
        #for 1Gi
        # 2 making a volume available for a container and the storage that will be used is the
        # mypvc
        # inside: mounting the mypvc using the path /usr/share/nginx/html